# Generated by Django 3.2 on 2022-07-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField(default=None)),
                ('weight', models.PositiveIntegerField(default=None)),
                ('height', models.PositiveIntegerField(default=None)),
                ('width', models.PositiveIntegerField(default=None)),
                ('length', models.PositiveIntegerField(default=None)),
            ],
        ),
    ]
