# Generated by Django 3.2 on 2022-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
